# Generated by Django 2.2.1 on 2019-10-01 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191001_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username_pk',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
